eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      password: '{cipher}AQARdzSBx9W9hpLrjLpdx8JHRtlxYSQ+SMD8WR9rZbR8NgznV4R1mAZ8utQLVmLPoyMynScT2APCZPmTkCE1OSEuhEF7kTJw6RK0tZe3cFX2OutkC79333ItLIjV5vstBcwSuHWwEgMh5GBWB/7gZoQsKhFnU0iHUIrzbOYqr7radzyTrGXHcaJz4Nz4TeXOFy0GiySZlIJMT0yHElpuYI1hrVSIerfwVK7l4aWvJGwOq2Q/fBfvHdqSkwlprXIHYlpvEoAC+P+SMDygoYOa/zighsF2cHrKXJwT1tO3WtRCDm8P8vrT7fMAQfVvAM7cm4LYM8tIKBqIiyQCwASS3Qv9snGnEFPdoolDO08ivwdsFFhc04bL24c+vAbkt30WDsc='
